# Generated by Django 2.2.2 on 2019-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190618_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Баланс клиента'),
        ),
    ]
