# Generated by Django 2.2.2 on 2019-06-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190618_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cardId',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='ИД карты клиента'),
        ),
    ]
