# Generated by Django 2.2.2 on 2020-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200824_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cardNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
