# Generated by Django 2.2.2 on 2019-06-19 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='terminal',
            new_name='terminalId',
        ),
        migrations.RemoveField(
            model_name='session',
            name='balance',
        ),
        migrations.AddField(
            model_name='session',
            name='clientId',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terminal',
            name='terminalId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Терминала'),
        ),
    ]
