# Generated by Django 2.2.2 on 2019-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0003_auto_20190623_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IP адрес'),
        ),
    ]
