# Generated by Django 2.2.2 on 2019-06-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('terminal', '0004_terminal_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='balance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='session',
            name='service',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='service.Service'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='balance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='terminalId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID'),
        ),
    ]
