# Generated by Django 2.2.2 on 2019-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_auto_20190623_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sessionId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Баланс'),
        ),
    ]
