# Generated by Django 2.2.2 on 2020-06-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_auto_20190723_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, default=0, null=True, verbose_name='Длительность')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость услуги')),
                ('sessionId', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='terminal.Session')),
            ],
        ),
    ]
