# Generated by Django 2.2.2 on 2020-06-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0007_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='balance',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='sessionId',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.Session'),
        ),
    ]
