# Generated by Django 2.2.2 on 2020-06-24 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('terminal', '0009_auto_20200624_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='service',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='service.Service'),
        ),
    ]
