# Generated by Django 2.2.2 on 2019-06-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код услуги')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название услуги')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ед. Измерения')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Стоимость')),
            ],
        ),
    ]
