# Generated by Django 2.2.2 on 2019-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название системы')),
                ('balance', models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='Баланс системы')),
            ],
        ),
    ]
