# Generated by Django 2.2.2 on 2019-06-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paysystem', '0003_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='StatusPay',
        ),
        migrations.AddField(
            model_name='pay',
            name='status',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='paysystem.StatusPay'),
        ),
    ]
