# Generated by Django 2.2.2 on 2020-08-20 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paysystem', '0004_auto_20190618_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='status',
        ),
        migrations.AddField(
            model_name='pay',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Время платежа'),
        ),
        migrations.CreateModel(
            name='Incas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата инкассации')),
                ('type', models.CharField(blank=True, default='', max_length=20, verbose_name='Тип инкассации')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
