# Generated by Django 2.2.2 on 2020-08-20 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paysystem', '0006_auto_20200820_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incas',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата инкассации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pay',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время платежа'),
            preserve_default=False,
        ),
    ]
